package com.ppwx.easysearch.qp;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.google.common.collect.Lists;
import com.ppwx.easysearch.core.function.normalize.GaussNormalizeFunc;
import com.ppwx.easysearch.core.similarity.LevenshteinDistanceSimilarity;
import com.ppwx.easysearch.qp.support.CustomStopChar;
import com.ppwx.easysearch.qp.util.PinyinUtil;
import org.junit.Test;

import java.util.ArrayList;
import java.util.IntSummaryStatistics;
import java.util.List;
import java.util.Map;
import java.util.OptionalDouble;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

public class Tester {

    @Test
    public void test() {
        String data = "[\n"
            + "        {\n"
            + "            \"keyword\": \"华为 OPhone\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 8557,\n"
            + "            \"productId\": 900,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 POCO Phone F1\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 2677,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 14 Pro\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 13067,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 14\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 4202,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 14 Pro\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 4203,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 Book Pro 14\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 12737,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 14 Plus\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 4281,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"测试苹果 iPhone 14\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 766910,\n"
            + "            \"productId\": 8278,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 14\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 13065,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 笔记本 Pro 14\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 7608,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 笔记本 Pro 14\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 18374,\n"
            + "            \"productId\": 7305,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 14 Pro Max\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 4204,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 笔记本 Pro X 14\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 16855,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 笔记本 Pro X 14\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 18374,\n"
            + "            \"productId\": 8324,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"ThinkPad neo 14\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 11518,\n"
            + "            \"productId\": 12655,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 - Pro\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 18374,\n"
            + "            \"productId\": 3471,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 - Pro\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 7619,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"华硕 破晓 Pro 14\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 8551,\n"
            + "            \"productId\": 5162,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 15\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 8355,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 7\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2555,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"华硕 无畏 14i 2023\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 8551,\n"
            + "            \"productId\": 12943,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"华硕 ROG Phone 7\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 8551,\n"
            + "            \"productId\": 16739,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 8\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2557,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 11\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2562,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 13\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 3706,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 4\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2545,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone SE\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2554,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 12\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 3354,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 5\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2546,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone X\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2559,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 6\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2550,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"华硕 无畏 Pro14\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 8551,\n"
            + "            \"productId\": 5211,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 14 Ultra\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 16873,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 13 Pro\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 3707,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 12 Pro\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 3352,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 5C\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2548,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 4S\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2549,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 6S\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2552,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 11i HyperCharge\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 15551,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 13 mini\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 3705,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone XR\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 134,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone XS\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2560,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 15 Pro\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 8357,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 12 mini\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 3355,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 5S\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2547,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 11 Pro\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2563,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone SE 2\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2565,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone SE 3\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 3953,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 3G\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2543,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"RedmiBook 14 II\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 18374,\n"
            + "            \"productId\": 7602,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 Civi\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 3839,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 米兔儿童电话手表5 Pro\",\n"
            + "            \"categoryId\": 12348,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 13819,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 Play\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 2691,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 Watch H1\",\n"
            + "            \"categoryId\": 12348,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 13118,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone XS Max\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2561,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 15 Plus\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 8356,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"RedmiBook 14 II\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 7606,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 7 Plus\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2556,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 8 Plus\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2558,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 3GS\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2544,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 6 Plus\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2551,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 Book Pro 16\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 12739,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"亚马逊Fire Phone\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 19018,\n"
            + "            \"productId\": 3083,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 6S Plus\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2553,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"华为 Bluetooth Headphones Lite AM61\",\n"
            + "            \"categoryId\": 842,\n"
            + "            \"brandId\": 8557,\n"
            + "            \"productId\": 13389,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"华硕 无畏 14\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 8551,\n"
            + "            \"productId\": 12779,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"华硕 ROG Zephyrus G14\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 8551,\n"
            + "            \"productId\": 5228,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 Buds 4 Pro\",\n"
            + "            \"categoryId\": 842,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 7223,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 蓝牙耳机 Pro\",\n"
            + "            \"categoryId\": 842,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 13457,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"华为 WATCH FIT new\",\n"
            + "            \"categoryId\": 12348,\n"
            + "            \"brandId\": 8557,\n"
            + "            \"productId\": 6991,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"亚马逊Fire Phone 2\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 19018,\n"
            + "            \"productId\": 3084,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"华为 P50 Pro (骁龙版)\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 8557,\n"
            + "            \"productId\": 3676,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 13 Pro Max\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 3708,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"RedmiBook Pro 14\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 7611,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"微软 Surface Headphones\",\n"
            + "            \"categoryId\": 842,\n"
            + "            \"brandId\": 17440,\n"
            + "            \"productId\": 13269,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 12 Pro Max\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 3353,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 11 Pro Max\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 2564,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"苹果 iPhone 15 Pro Max\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 14026,\n"
            + "            \"productId\": 8358,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"vivo TWS Earphone\",\n"
            + "            \"categoryId\": 842,\n"
            + "            \"brandId\": 25591,\n"
            + "            \"productId\": 13449,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"RedmiBook Pro 14\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 18374,\n"
            + "            \"productId\": 7205,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 13 Pro\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 4434,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 笔记本 Pro 15\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 7612,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 11 Pro\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 3631,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 笔记本 Pro 15\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 18374,\n"
            + "            \"productId\": 7164,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"Yota Phone YOTA 3\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 280152,\n"
            + "            \"productId\": 3339,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"ThinkPad ThinkBook 14p 2022\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 11518,\n"
            + "            \"productId\": 4558,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 CC 9 Pro\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 2737,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 笔记本 Pro X 15\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 7609,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 Buds 3T Pro\",\n"
            + "            \"categoryId\": 842,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 14113,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"ThinkBook 14\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 11518,\n"
            + "            \"productId\": 3390,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"华硕 VivoBook Flip 14\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 8551,\n"
            + "            \"productId\": 5310,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 Pad 6 Max 14\",\n"
            + "            \"categoryId\": 2694,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 15038,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"ThinkPad ThinkBook 14p 2021\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 11518,\n"
            + "            \"productId\": 4605,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 Mi Note 10\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 2756,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 Note 10 Pro\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 2746,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 12S Pro\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 4134,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 笔记本 Pro X 15\",\n"
            + "            \"categoryId\": 672,\n"
            + "            \"brandId\": 18374,\n"
            + "            \"productId\": 7261,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 FlipBuds pro\",\n"
            + "            \"categoryId\": 842,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 7493,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"Redmi Buds 3 Pro\",\n"
            + "            \"categoryId\": 842,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 13673,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        },\n"
            + "        {\n"
            + "            \"keyword\": \"小米 13T Pro\",\n"
            + "            \"categoryId\": 655,\n"
            + "            \"brandId\": 133787,\n"
            + "            \"productId\": 13889,\n"
            + "            \"score\": null,\n"
            + "            \"tagList\": []\n"
            + "        }\n"
            + "    ]";
        String keyword = "iphone14";
        final JSONArray array = JSON.parseArray(data);
        final LevenshteinDistanceSimilarity levenshteinDistanceSimilarity = new LevenshteinDistanceSimilarity(20);
        array.forEach(obj -> {
            final Double score = levenshteinDistanceSimilarity.apply(((JSONObject) obj).getString("keyword"),
                keyword,
                CustomStopChar::isStopChar);
            System.out.println(((JSONObject) obj).getString("keyword") + " > " + score);
        });

    }

    @Test
    public void testLog() {
        // 分段处理
        // 0.9-1.0 时直接不进行调整
        // 0.7-0.8 时相关性 + 0.2 * 销量分值
        // 0.5-0.7 时相关性 + 0.3 * 销量分值
        // 小于0.5 时相关性 + 0.4 * 销量分值
        final LevenshteinDistanceSimilarity levenshteinDistanceSimilarity = new LevenshteinDistanceSimilarity(20);
        System.out.println(levenshteinDistanceSimilarity.apply("15", "OPPO 15", CustomStopChar::isStopChar));
    }

    @Test
    public void testSales() {
        List<Integer> list = Lists.newArrayList(1, 50, 233, 2342,12);
        final double avg = list.stream().mapToInt(v -> v).average().orElse(0.0d);
        final double variance = list.stream().mapToDouble(v -> Math.pow(v - avg, 2)).average().orElse(0.0d);
        double standardDeviation = Math.sqrt(variance);
        GaussNormalizeFunc func = new GaussNormalizeFunc(1000, standardDeviation);
        System.out.println(func.score(1));
        System.out.println(func.score(233));
        System.out.println(func.score(2342));
        System.out.println(func.score(12));
    }

    @Test
    public void testGetPinyin() {
        // TC01: 基础中文
        assertEquals("ni hao", PinyinUtil.getPinyin("你好", " "));

        // TC02: 中英文混合
        assertEquals("hello-shi-jie", PinyinUtil.getPinyin("hello世界", "-"));

        // TC03: 品牌 + 数字组合
        assertEquals("huawei Mate 40", PinyinUtil.getPinyin("华为 Mate 40", ""));

        // TC04: 自定义分隔符
        assertEquals("xiao,mi,Note10", PinyinUtil.getPinyin("小米Note10", ","));

        // TC05: 英文单词不转拼音
        assertEquals("iPhone 14 Pro", PinyinUtil.getPinyin("iPhone 14 Pro", " "));

        // TC06: 空白字符
        assertEquals("  ", PinyinUtil.getPinyin("  ", ""));

        // TC08: 标点符号
        assertEquals("biao+dian+!@#$%^&*", PinyinUtil.getPinyin("标点!@#$%^&*", "+"));

        // TC09: 数字不转拼音
        assertEquals("shu+zi+123456", PinyinUtil.getPinyin("数字123456", "+"));

        // TC07: null 输入（根据你的逻辑决定抛异常还是返回空）
        try {
            assertNull(PinyinUtil.getPinyin(null, " "));
        } catch (Exception e) {
            // 如果允许null输入并返回空，则改为：
            // assertEquals("", PinyinUtil.getPinyin(null, " "));
        }
    }

    @Test
    public void testGetPinyin2() {
        for (char i = '\u4E00'; i <= '\u9FA5'; i++) {
            PinyinUtil.getPinyin(String.valueOf(i));
        }
    }

}
